---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: true
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_stdout_callback: yaml
  roles:
    - deploy
