- name: Update/upgrade packages
  ansible.builtin.apt:
    update_cache: yes

- name: Install nodejs, npm, and pm2.
  ansible.builtin.command: "{{ item }}"
  with_items:
    - curl -sL https://deb.nodesource.com/setup_14.x -o nodesource_setup.sh
    - bash nodesource_setup.sh
    - apt install -y nodejs
    - node -v

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present