- name: Update/upgrade packages
  become: true
  become_method: sudo
  become_user: root  
  apt:
    update_cache: yes

# - name: curl nvm
#   command: curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh -o install.sh 

# - name: chmod install.sh
#   command: chmod 777 install.sh

# - name: run install.sh
#   command: /home/ubuntu/install.sh

# - name: source profile
#   # command: source ~/.bashrc
#   shell: . /home/ubuntu/.bashrc && pwd

# - name: Install nodejs, npm
#   command: nvm install 12.16

# - name: "install pm2"
#   become: true
#   npm:
#     name: pm2
#     global: yes
#     production: yes
#     state: present

- name: Install nodejs, npm, and pm2.
  become: true
  become_method: sudo
  become_user: root 
  ansible.builtin.command: "{{ item }}"
  with_items:
    - curl -sL https://deb.nodesource.com/setup_14.x -o nodesource_setup.sh
    - bash nodesource_setup.sh
    - apt install -y nodejs
    - node -v
    - apt install -y build-essential
    - npm install pm2 -g