- name: Update/upgrade packages
  ansible.builtin.apt:
    update_cache: yes

- name: Install nodejs, npm, and pm2.
  ansible.builtin.command: "{{ item }}"
  with_items:
    - cd
    - curl -sL https://deb.nodesource.com/setup_14.x -o nodesource_setup.sh
    - bash nodesource_setup.sh
    - apt install -y nodejs
    - node -v
    - apt install -y build-essential
    - curl -sL https://raw.githubusercontent.com/Unitech/pm2/master/packager/setup.deb.sh | bash -