- name: Update/upgrade packages
  become: true
  become_method: sudo
  become_user: root  
  apt:
    update_cache: yes

- name: Install nodejs, npm
  command: "{{ item }}"
  with_items:
    - curl -sL https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh -o install_nvm.sh
    - bash install_nvm.sh
    - "export NVM_DIR=$HOME/.nvm"
    - "[ -s $NVM_DIR/nvm.sh ] && \. $NVM_DIR/nvm.sh"
    - "[ -s $NVM_DIR/bash_completion ] && \. $NVM_DIR/bash_completion"
    - source ~/.bash_profile
    - nvm install 12.16

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present