- name: Update/upgrade packages
  become: true
  become_method: sudo
  become_user: root  
  apt:
    update_cache: yes

- name: curl nvm
  command: curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash

- name: source profile
  command: source ~/.bashrc

- name: Install nodejs, npm
  command: nvm install 12.16

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present