- name: Update/upgrade packages
  ansible.builtin.apt:
    update_cache: yes

- name: Install nodejs, npm, and pm2.
  ansible.builtin.command: "{{ item }}"
  with_items:
    - cd
    - curl -sL https://deb.nodesource.com/setup_14.x -o nodesource_setup.sh
    - sudo bash nodesource_setup.sh
    - sudo apt install -y nodejs
    - node -v
    - sudo apt install -y build-essential
    - sudo npm install pm2@latest -g