- name: Extract tar file to server
  unarchive:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu

- name: check env
  command: env
  register: check_env

- name: debug env 
  debug: msg="{{ check_env.stdout }}"

- name: pm2 start npm -- start
  command: pm2 start npm -- start
