- name: Extract tar file to server
  unarchive:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu

- name: npm install
  command: npm install

# - name: pm2 stop default
#   command: pm2 stop default

- name: pm2 start npm -- start
  command: pm2 start npm -- start
