- name: Extract tar file to server
  unarchive:
    src: /root/project/artifact.tar.gz
    dest: ~/

- name: check env
  command: env
  register: check_env

- name: debug env 
  debug: msg="{{ check_env.stdout }}"

- name: copy env to file
  copy:
    content: "{{ check_env.stdout }}"
    dest: "/tmp/test.txt"

- name: npm install
  command: npm install

- name: pm2 start npm -- start
  command: pm2 start npm -- run start
  register: check_pm2

- name: debug pm2
  debug: msg="{{ check_pm2.stdout }}"

- name: List all ports
  command: netstat -tulpn | grep LISTEN
  register: check_port

- name: debug ports 
  debug: msg="{{ check_port.stdout }}"