- name: Extract tar file to server
  unarchive:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu

- name: check env
  command: env
  register: check_env

- name: debug env 
  debug: msg="{{ check_env.stdout }}"

- name: copy env to file
  copy:
    content: "{{ check_env.stdout }}"
    dest: "/tmp/test.txt"

- name: pm2 stop 
  command: pm2 stop default

- name: pm2 start npm -- start
  command: pm2 start npm -- start

- name: List all ports
  debug:
    msg: "{{ (ansible_facts.tcp_listen + ansible_facts.udp_listen) | map(attribute='port') | unique | sort | list }}"